
version: "3.9"
services:
  scamgeo:
    build: .
    container_name: scamgeo_banking
    environment:
      - LOG_LEVEL=INFO
      - TELEGRAM_API_ID=${TELEGRAM_API_ID}
      - TELEGRAM_API_HASH=${TELEGRAM_API_HASH}
      - VT_API_KEY=${VT_API_KEY}
      - OTX_API_KEY=${OTX_API_KEY}
    volumes:
      - ./out:/out
    working_dir: /app
    command: ["python","-m","scamgeo_banking.cli.app","version"]
